# Generated by Django 3.0.3 on 2020-02-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('address', models.TextField()),
                ('city', models.IntegerField(unique=True)),
                ('geo_coords', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('login', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_order.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='make_order.Place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_order.Service'),
        ),
        migrations.CreateModel(
            name='OrderTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=15)),
                ('finish_time', models.CharField(max_length=15)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_order.Schedule')),
                ('sp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='make_order.SP')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesOfOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='../static/images/')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_order.Office')),
            ],
        ),
    ]
