# Generated by Django 3.0.3 on 2020-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0005_order_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='info',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
