# Generated by Django 3.0.3 on 2020-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0006_auto_20200219_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='long',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='service',
            name='info',
            field=models.TextField(default='.'),
        ),
    ]
