# Generated by Django 3.0.3 on 2020-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0007_auto_20200224_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='fin_time',
            field=models.CharField(default='18:00', max_length=40),
        ),
        migrations.AddField(
            model_name='office',
            name='st_time',
            field=models.CharField(default='08:00', max_length=40),
        ),
    ]
