# Generated by Django 3.0.3 on 2020-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0009_auto_20200302_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=0, upload_to='../static/images/'),
        ),
    ]
