# Generated by Django 3.0.3 on 2020-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0010_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
