# Generated by Django 3.0.4 on 2020-03-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0011_order_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default=0, upload_to='welcome/static/images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='make_order.Group'),
        ),
    ]
