# Generated by Django 3.0.4 on 2020-03-17 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0012_auto_20200317_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ServiceGroup',
        ),
    ]
