# Generated by Django 3.0.4 on 2020-03-17 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0015_auto_20200317_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
