# Generated by Django 3.0.4 on 2020-03-17 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0016_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='group_name',
        ),
    ]
