# Generated by Django 3.0.4 on 2020-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0017_auto_20200317_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='group_name',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
