# Generated by Django 3.0.4 on 2020-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0023_auto_20200317_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
