# Generated by Django 3.0.4 on 2020-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0025_auto_20200317_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
