# Generated by Django 3.0.4 on 2020-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0026_auto_20200317_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
