# Generated by Django 3.0.4 on 2020-03-18 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0027_auto_20200317_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
