# Generated by Django 3.0.4 on 2020-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0028_auto_20200318_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesofoffice',
            name='office',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='office',
        ),
        migrations.DeleteModel(
            name='ImagesOfOffice',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
