# Generated by Django 3.0.4 on 2020-03-18 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0031_auto_20200318_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ServiceGroup',
        ),
    ]
