# Generated by Django 3.0.4 on 2020-03-18 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0033_auto_20200318_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
