# Generated by Django 3.0.4 on 2020-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0034_auto_20200318_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
