# Generated by Django 3.0.4 on 2020-03-18 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0038_auto_20200318_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='group',
        ),
        migrations.DeleteModel(
            name='ServiceGroup',
        ),
    ]
