# Generated by Django 3.0.4 on 2020-03-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0039_auto_20200318_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
