# Generated by Django 3.0.4 on 2020-03-18 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0041_service_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='group',
        ),
    ]
