# Generated by Django 3.0.4 on 2020-03-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0042_remove_service_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='make_order.ServiceGroup'),
        ),
    ]
