# Generated by Django 3.0.4 on 2020-03-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0044_auto_20200318_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE,
                                    to='make_order.ServiceGroup'),
        ),
    ]
