# Generated by Django 3.0.4 on 2020-03-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0048_auto_20200318_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_order.Place'),
        ),
    ]
