# Generated by Django 3.0.4 on 2020-03-19 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('make_order', '0050_auto_20200319_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='group',
        ),
    ]
